---
title: "DataViz Makeover 1"
description: |
  DataViz Makeover for ISSS608: Visual Analytics
author:
  - name: Vertika Poddar
    url: https://example.com/norajones
date: 05-22-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
#1.	BACKGROUND
The original visualization is created from the data provided by the Department of Statistics, Singapore (DOS).
Context / Key takeaways - ?

#2.	Critiques and suggestions for the original visualization (table format)
##2.1 Clarity
S/N	CRITIQUES	COMMENTS / SUGGETIONS
1.	Graph Title – The title of the graph mentions the timeline as 2019-2020 which is ambiguous as the graph represents the data of two years.	The title of the graph should be such as it gives 
2.	Use of different scale – Two different scale has been used to plot export and import data. This leads to misinterpretation and misrepresentation.	
3.	Incorrect axis title – The title of X Axis is ‘Month of Period’ whereas the X Axis label is that of the year. The title of the axis is not in sync with the labels.	
4.	Data not comparable – A separate graph for each country makes the comparison across countries difficult and in-turn makes the graph less handy and useful.	
5.	Currency not mentioned - 	
6.	Graph for Japan is misleading	
7.	Source of the data not mentioned	

##2.2 Aesthetics
S/N	CRITIQUES	COMMENTS / SUGGETIONS
1.	Different fonts – Three different fonts have been used in the graph for the Axis Title, Axis Label and Graph Title.	The text used in the graph should belong to the same font family. Moreover, the font should not be fancy and should be easy to read and understand.
2.	Multiple axis for value – Two separate axis to represent export and import.	The use of two separate value axis makes the graph complicated, confusing, and clumsy. The graph should be clear and pleasing to the eye.
3.	No tick marks in the X and Y Axis 	



